---
# Default variables for Nginx role

nginx_worker_processes: auto
nginx_worker_connections: 2048
nginx_client_max_body_size: 100M

# SSL
nginx_ssl_protocols: "TLSv1.2 TLSv1.3"
nginx_ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384"
nginx_ssl_prefer_server_ciphers: "off"

# Virtual hosts
nginx_vhosts:
  - server_name: "{{ ansible_host }}"
    listen_port: 80
    proxy_pass: "http://localhost:{{ odoo_port }}"
    locations:
      - path: /
        proxy_settings:
          - "proxy_redirect off"
          - "proxy_set_header X-Forwarded-Host $host"
          - "proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for"
          - "proxy_set_header X-Forwarded-Proto $scheme"
          - "proxy_set_header X-Real-IP $remote_addr"
