---
# Default variables for Redis role

redis_bind_interface: "0.0.0.0"
redis_protected_mode: "yes"
redis_password: "{{ lookup('env', 'REDIS_PASSWORD') | default('', true) }}"
redis_databases: 16
redis_save:
  - "900 1"
  - "300 10"
  - "60 10000"
redis_appendonly: "yes"
redis_appendfsync: "everysec"
