---
all:
  children:
    odoo_servers:
      hosts:
        odoo-prod-01:
          ansible_host: 194.87.235.33
          ansible_user: bozzyk44
          ansible_port: 22
          server_role: primary
          ansible_ssh_private_key_file

    kkt_adapters:
      hosts:
        kkt-adapter-01:
          ansible_host: 194.87.235.33
          ansible_user: bozzyk44
          pos_location: store_01

    db_servers:
      hosts:
        db-prod-01:
          ansible_host: 194.87.235.33
          ansible_user: bozzyk44

    monitoring_servers:
      hosts:
        monitoring-01:
          ansible_host: 194.87.235.33
          ansible_user: bozzyk44

  vars:
    ansible_python_interpreter: /usr/bin/python3
    deployment_env: production
