---
all:
  children:
    odoo_servers:
      hosts:
        odoo-staging-01:
          ansible_host: 192.168.1.50
          ansible_user: deploy
          ansible_port: 22

    kkt_adapters:
      hosts:
        kkt-adapter-staging-01:
          ansible_host: 192.168.1.51
          ansible_user: deploy
          pos_location: test_store

  vars:
    ansible_python_interpreter: /usr/bin/python3
    deployment_env: staging
